FROM node:alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json yarn.lock ./
COPY ./src ./src
COPY ./public ./public
RUN yarn install
RUN NODE_OPTIONS="--max-old-space-size=8192" yarn build

FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY ./nginx.default.conf /etc/nginx/conf.d/default.conf
