FROM python:3.9
WORKDIR /app

ADD api/application ./application
RUN mkdir ./dbVol
COPY api/requirements.txt api/wsgi.py api/.env api/config.py ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "wsgi:app"]
